Repository AY2021S1-CS2113T-W13-3/tp, pull requests merged in 2020-11, with the labels that each got.

#156 Initial Fix of PED Implementation Bugs
  docs/UserGuide.md
  src/main/java/seedu/duke/logic/commands/circuit/AddCircuitCommand.java
  src/main/java/seedu/duke/logic/commands/circuit/SetCircuitCommand.java
  src/main/java/seedu/duke/logic/commands/gates/CalculateBooleanCommand.java
  src/main/java/seedu/duke/logic/commands/gates/SetBooleanCommand.java
  src/main/java/seedu/duke/logic/parser/BooleanParser.java
  src/main/java/seedu/duke/logic/parser/Parser.java
  src/main/java/seedu/duke/model/gates/AndGate.java
  src/main/java/seedu/duke/model/gates/Gate.java
  src/main/java/seedu/duke/model/gates/NandGate.java
  src/main/java/seedu/duke/model/gates/NorGate.java
  src/main/java/seedu/duke/model/gates/OrGate.java
  src/main/java/seedu/duke/model/gates/XnorGate.java
  src/main/java/seedu/duke/model/gates/XorGate.java
  src/main/java/seedu/duke/model/template/BooleanTemplate.java
  src/main/java/seedu/duke/model/template/CircuitTemplate.java
  src/main/java/seedu/duke/model/template/LcTemplate.java
  src/main/java/seedu/duke/model/template/LrTemplate.java
  src/main/java/seedu/duke/model/template/RTemplate.java
  src/main/java/seedu/duke/model/template/RcTemplate.java
  src/main/java/seedu/duke/ui/Ui.java
  src/test/java/seedu/duke/logic/commands/gates/CalculateBooleanCommandTest.java
  src/test/java/seedu/duke/logic/commands/gates/SetBooleanCommandTest.java
  src/test/java/seedu/duke/model/binarytree/BinaryTreeTest.java
  src/test/java/seedu/duke/model/gates/GateTest.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High, severity.High, type.Bug, type.Enhancement, type.Story

#158 Initial Fix of PED User Guide Bugs
  docs/DeveloperGuide.md
  docs/SettingUp.md
  docs/UserGuide.md
Labels: priority.High, severity.High, type.Bug, type.Documentation

#157 Refactor Logic Exceptions
  src/main/java/seedu/duke/logic/commands/TutorialCommand.java
  src/main/java/seedu/duke/logic/commands/circuit/AddCircuitCommand.java
  src/main/java/seedu/duke/logic/commands/circuit/CircuitCommand.java
  src/main/java/seedu/duke/logic/commands/circuit/TutorialCircuitCommand.java
  src/main/java/seedu/duke/logic/commands/exceptions/CommandException.java
  src/main/java/seedu/duke/logic/commands/exceptions/ComponentNotSetException.java
  src/main/java/seedu/duke/logic/commands/exceptions/IncorrectCommandException.java
  src/main/java/seedu/duke/logic/commands/gates/BooleanCommand.java
  src/main/java/seedu/duke/logic/commands/gates/TutorialBooleanCommand.java
  src/main/java/seedu/duke/logic/parser/BooleanParser.java
  src/main/java/seedu/duke/logic/parser/CircuitParser.java
  src/main/java/seedu/duke/logic/parser/Parser.java
  src/main/java/seedu/duke/logic/parser/exceptions/InvalidArgumentException.java
  src/main/java/seedu/duke/logic/parser/exceptions/InvalidCommandException.java
  src/main/java/seedu/duke/logic/parser/exceptions/InvalidGateException.java
  src/main/java/seedu/duke/logic/parser/exceptions/InvalidInputException.java
  src/main/java/seedu/duke/logic/parser/exceptions/InvalidNumberException.java
  src/main/java/seedu/duke/logic/parser/exceptions/InvalidPositionException.java
  src/main/java/seedu/duke/logic/parser/exceptions/InvalidTemplateException.java
  src/main/java/seedu/duke/logic/parser/exceptions/NoTemplateException.java
  src/main/java/seedu/duke/logic/parser/exceptions/NotEnoughArgumentsException.java
  src/main/java/seedu/duke/logic/parser/exceptions/ParserException.java
  src/test/java/seedu/duke/logic/parser/BooleanParserTest.java
  src/test/java/seedu/duke/logic/parser/CircuitParserTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High, severity.Medium, type.Bug, type.Enhancement

#159 Update Wira PPP
  docs/DeveloperGuide.md
  docs/SettingUp.md
  docs/UserGuide.md
  docs/diagrams/CalcBooleanCommand.png
  docs/diagrams/CalcBooleanCommand.puml
  docs/diagrams/CheckIndexSequence.png
  docs/diagrams/CheckIndexSequence.puml
  docs/diagrams/SetIndexSequence.png
  docs/diagrams/SetIndexSequence.puml
  docs/diagrams/SetSequenceDiagram.png
  docs/team/hughjazzman.md
Labels: priority.High, type.Documentation

#160 A Exception Customisation
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/logic/commands/SummaryCommand.java
  src/main/java/seedu/duke/logic/commands/circuit/AddCircuitCommand.java
  src/main/java/seedu/duke/logic/commands/circuit/SetCircuitCommand.java
  src/main/java/seedu/duke/logic/commands/circuit/TutorialCircuitCommand.java
  src/main/java/seedu/duke/logic/commands/exceptions/IncorrectCommandException.java
  src/main/java/seedu/duke/logic/commands/gates/CalculateBooleanCommand.java
  src/main/java/seedu/duke/logic/parser/exceptions/InvalidArgumentException.java
  src/main/java/seedu/duke/logic/parser/exceptions/InvalidTemplateException.java
  src/main/java/seedu/duke/model/binarytree/BinaryTree.java
  src/main/java/seedu/duke/model/component/Component.java
  src/main/java/seedu/duke/model/component/LoadComponent.java
  src/main/java/seedu/duke/model/exceptions/binarytreeexceptions/BinaryTreeException.java
  src/main/java/seedu/duke/model/exceptions/binarytreeexceptions/BinaryTreeInvalidIndexException.java
  src/main/java/seedu/duke/model/exceptions/componentexceptions/ComponentException.java
  src/main/java/seedu/duke/model/exceptions/componentexceptions/ZeroComponentException.java
  src/main/java/seedu/duke/model/exceptions/gatesexceptions/GateException.java
  src/main/java/seedu/duke/model/exceptions/gatesexceptions/InputsNotSetException.java
  src/main/java/seedu/duke/model/exceptions/templateexceptions/GateSetException.java
  src/main/java/seedu/duke/model/exceptions/templateexceptions/GatesToChannelsException.java
  src/main/java/seedu/duke/model/exceptions/templateexceptions/InputNotSetException.java
  src/main/java/seedu/duke/model/exceptions/templateexceptions/InvalidComponentException.java
  src/main/java/seedu/duke/model/exceptions/templateexceptions/ParentGateNotSetException.java
  src/main/java/seedu/duke/model/exceptions/templateexceptions/TemplateComponentsNotSetException.java
  src/main/java/seedu/duke/model/exceptions/templateexceptions/TemplateException.java
  src/main/java/seedu/duke/model/gates/AndGate.java
  src/main/java/seedu/duke/model/gates/Gate.java
  src/main/java/seedu/duke/model/gates/NandGate.java
  src/main/java/seedu/duke/model/gates/NorGate.java
  src/main/java/seedu/duke/model/gates/OrGate.java
  src/main/java/seedu/duke/model/gates/XnorGate.java
  src/main/java/seedu/duke/model/gates/XorGate.java
  src/main/java/seedu/duke/model/template/BooleanTemplate.java
  src/main/java/seedu/duke/model/template/CircuitTemplate.java
  src/main/java/seedu/duke/model/template/LcTemplate.java
  src/main/java/seedu/duke/model/template/LrTemplate.java
  src/main/java/seedu/duke/model/template/RTemplate.java
  src/main/java/seedu/duke/model/template/RcTemplate.java
  src/main/java/seedu/duke/ui/Ui.java
  src/test/java/seedu/duke/logic/commands/circuit/CalculateCircuitCommandTest.java
  src/test/java/seedu/duke/logic/commands/circuit/SetCircuitCommandTest.java
  src/test/java/seedu/duke/model/binarytree/BinaryTreeTest.java
  src/test/java/seedu/duke/model/component/CapacitorTest.java
  src/test/java/seedu/duke/model/component/InductorTest.java
  src/test/java/seedu/duke/model/component/LoadComponentTest.java
  src/test/java/seedu/duke/model/component/ResistorTest.java
  src/test/java/seedu/duke/model/component/VoltageSourceTest.java
  src/test/java/seedu/duke/model/gates/GateTest.java
  src/test/java/seedu/duke/model/template/LcTemplateTest.java
  src/test/java/seedu/duke/model/template/LrTemplateTest.java
  src/test/java/seedu/duke/model/template/RTemplateTest.java
  src/test/java/seedu/duke/model/template/RcTemplateTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.Medium, severity.High, type.Bug, type.Enhancement

#161 Changes to Ui concerning Boolean Tutorial
  docs/DeveloperGuide.md
  src/main/java/seedu/duke/logic/commands/SummaryCommand.java
  src/main/java/seedu/duke/logic/commands/gates/TutorialBooleanCommand.java
  src/main/java/seedu/duke/ui/Ui.java
  src/test/java/seedu/duke/model/template/LcTemplateTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/runtest.bat
  unused/RemovedUi.java
Labels: priority.High, severity.Medium, type.Bug, type.Enhancement

#162 Changes to Tutorial section of User Guide
  .gitignore
  docs/UserGuide.md
  docs/diagrams/BadCommand.png
  docs/diagrams/TutorialMode.png
Labels: priority.High, severity.Low, type.Bug, type.Documentation

#165 Merged Master Changes with my Branch AAAAAAAAAAAAAAA
  docs/diagrams/BinaryTreeInsertSequenceDiagram.png
  docs/diagrams/BinaryTreeInsertSequenceDiagram.puml
  docs/diagrams/BinaryTreeIsLeafSequence.png
  docs/diagrams/BinaryTreeIsLeafSequence.puml
  docs/team/sevenseasofbri.md
  src/main/java/seedu/duke/logic/commands/circuit/AddCircuitCommand.java
  src/main/java/seedu/duke/logic/commands/circuit/SetCircuitCommand.java
  src/main/java/seedu/duke/logic/commands/circuit/TutorialCircuitCommand.java
  src/main/java/seedu/duke/logic/commands/gates/TutorialBooleanCommand.java
  src/main/java/seedu/duke/logic/parser/exceptions/InvalidPositionException.java
  src/main/java/seedu/duke/model/exceptions/templateexceptions/InvalidComponentException.java
  src/main/java/seedu/duke/ui/Ui.java
  src/test/java/seedu/duke/model/binarytree/BinaryTreeTest.java
  text-ui-test/EXPECTED.TXT
Labels: priority.Medium, severity.Medium, type.Bug, type.Documentation, type.Enhancement

#116 Update Dev Guide With Circuit Implementation Considerations
  docs/DeveloperGuide.md
Labels: priority.Medium, type.Documentation

#168 Update UG with assigned images and complete PPP.
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/BooleanCalc.png
  docs/diagrams/ByeCommand.png
  docs/diagrams/CircutiCalc.png
  docs/team/sevenseasofbri.md
  src/main/java/seedu/duke/model/gates/AndGate.java
  src/main/java/seedu/duke/model/gates/NandGate.java
  src/main/java/seedu/duke/model/gates/NorGate.java
  src/main/java/seedu/duke/model/gates/OrGate.java
  src/main/java/seedu/duke/model/gates/XnorGate.java
  src/main/java/seedu/duke/model/gates/XorGate.java
Labels: priority.Medium, type.Documentation

#173 Update Formatting
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/SetBooleanLabel.png
  docs/diagrams/SetCircuitLabel.png
  docs/team/hughjazzman.md
  docs/team/praveenelango.md
Labels: priority.High, type.Documentation

#171 Include Praveen's PPP
  docs/team/praveenelango.md
Labels: priority.High, type.Documentation

#169 UG - Include labelled images for set functions
  docs/UserGuide.md
  docs/diagrams/SetBooleanLabel.png
  docs/diagrams/SetCircuitLabel.png
Labels: priority.Medium, type.Documentation

#170 Add TemplateBooleanAnd (annotated)
  docs/UserGuide.md
  docs/diagrams/TemplateBooleanAnd.png
Labels: priority.Medium, type.Documentation

#172 Add Dorian PPP
  docs/AboutUs.md
  docs/team/dorianfong98.md
Labels: priority.Medium, type.Documentation

#176 Circuit Tutorial Fixes
  src/main/java/seedu/duke/ui/Ui.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High, severity.High, type.Bug, type.Enhancement

#166 Dash PPP
  docs/team/oasisbeatle.md
Labels: priority.High, type.Documentation

#178 update circuit tutorial
  src/main/java/seedu/duke/logic/commands/circuit/TutorialCircuitCommand.java
  src/main/java/seedu/duke/ui/Ui.java
  text-ui-test/EXPECTED.TXT
Labels: severity.Medium, type.Bug

#182 Update dorianfong98.md
  docs/team/dorianfong98.md
Labels: priority.Medium, severity.VeryLow, type.Bug, type.Documentation

#183 Update Minor Changes
  docs/UserGuide.md
Labels: priority.Medium, severity.Low, type.Bug, type.Documentation

#184 Update App Name
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.High, severity.High, type.Bug, type.Documentation

#185 Last min fixes to summary and tutorial
  docs/UserGuide.md
  docs/diagrams/Summary.png
  docs/diagrams/SummaryCommand.png
  src/main/java/seedu/duke/logic/commands/SummaryCommand.java
  src/main/java/seedu/duke/logic/commands/circuit/TutorialCircuitCommand.java
  src/main/java/seedu/duke/logic/commands/gates/TutorialBooleanCommand.java
  text-ui-test/EXPECTED.TXT
Labels: priority.Medium, type.Bug, type.Documentation, type.Enhancement

#181 Update AboutUs.md
  docs/AboutUs.md
Labels: priority.Medium, severity.Medium, type.Bug, type.Documentation

#186 Update oasisbeatle.md
  docs/team/oasisbeatle.md
Labels: priority.Medium, type.Documentation

#187 Update input, gate
  docs/UserGuide.md
Labels: priority.Medium, severity.Low, type.Bug, type.Documentation

#190 Update UG blame
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.Medium, type.Documentation
