Repository AY2021S1-CS2113T-W13-3/tp, pull requests merged in 2020-10, with the labels that each got.

#13 A- About Us
  docs/AboutUs.md
  src/main/java/seedu/duke/component/Inductor.java
Labels: priority.Medium, type.Documentation

#11 Add Increment A-Inductor
  src/main/java/seedu/duke/component/Inductor.java
Labels: priority.High, type.Enhancement

#14 Update AboutUs.md
  docs/AboutUs.md
  docs/team/wira.md
Labels: priority.Medium, type.Documentation

#15 John doe About Us
  docs/AboutUs.md
Labels: priority.Medium, type.Documentation

#17 Fix table AboutUs.md
  docs/AboutUs.md
Labels: priority.Medium, severity.VeryLow, type.Bug, type.Documentation

#21 Add A-VoltageSource
  src/main/java/seedu/duke/component/VoltageSource.java
Labels: priority.High, type.Enhancement

#19 Add A-Resistor
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  src/main/java/seedu/duke/component/Resistor.java
Labels: priority.High, type.Enhancement

#24 Introduce Add Component
  src/main/java/seedu/duke/commands/AddCommand.java
  src/main/java/seedu/duke/component/Capacitor.java
  src/main/java/seedu/duke/component/Component.java
  src/main/java/seedu/duke/component/Inductor.java
  src/main/java/seedu/duke/component/LoadComponent.java
  src/main/java/seedu/duke/component/Resistor.java
  src/main/java/seedu/duke/component/VoltageSource.java
  src/main/java/seedu/duke/parser/Parser.java
Labels: priority.High, type.Story

#23 Add A-Template, A-LrTemplate
  src/main/java/seedu/duke/template/LrTemplate.java
  src/main/java/seedu/duke/template/Template.java
Labels: priority.High, type.Enhancement

#27 Added RTemplate, refactored RL to extend R instead of default
  src/main/java/seedu/duke/template/LrTemplate.java
  src/main/java/seedu/duke/template/RTemplate.java
Labels: priority.High, type.Story

#28 A-LcTemplate
  src/main/java/seedu/duke/template/LcTemplate.java
Labels: priority.High, type.Story

#26 Add Rc-Template
  src/main/java/seedu/duke/template/RcTemplate.java
Labels: priority.High, type.Story

#25 Add TemplateCommand with parsing, ExitCommand
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/commands/AddCommand.java
  src/main/java/seedu/duke/commands/Command.java
  src/main/java/seedu/duke/commands/ExitCommand.java
  src/main/java/seedu/duke/commands/TemplateCommand.java
  src/main/java/seedu/duke/component/Component.java
  src/main/java/seedu/duke/parser/Parser.java
  src/main/java/seedu/duke/template/LrTemplate.java
  src/main/java/seedu/duke/template/Template.java
  src/main/java/seedu/duke/ui/Ui.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High, type.Story

#31 Add getImpedance() for RTemplate
  src/main/java/seedu/duke/template/LrTemplate.java
  src/main/java/seedu/duke/template/RTemplate.java
Labels: priority.High, severity.VeryLow, type.Bug, type.Story

#30 Add getImpedance and angularFrequency
  src/main/java/seedu/duke/template/LrTemplate.java
  src/main/java/seedu/duke/template/Template.java
Labels: priority.High, type.Enhancement

#32 Add getImpedance() for RcTemplate
  src/main/java/seedu/duke/template/RcTemplate.java
Labels: priority.High, type.Story

#35 Add setters
  src/main/java/seedu/duke/template/LcTemplate.java
  src/main/java/seedu/duke/template/LrTemplate.java
  src/main/java/seedu/duke/template/RTemplate.java
  src/main/java/seedu/duke/template/RcTemplate.java
Labels: priority.High, type.Story

#36 Complete Add/Set Command, JUnit Tests
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/commands/AddCommand.java
  src/main/java/seedu/duke/commands/Command.java
  src/main/java/seedu/duke/commands/ExitCommand.java
  src/main/java/seedu/duke/commands/SetCommand.java
  src/main/java/seedu/duke/commands/TemplateCommand.java
  src/main/java/seedu/duke/component/LoadComponent.java
  src/main/java/seedu/duke/parser/Parser.java
  src/main/java/seedu/duke/template/LcTemplate.java
  src/main/java/seedu/duke/template/LrTemplate.java
  src/main/java/seedu/duke/template/RTemplate.java
  src/main/java/seedu/duke/template/RcTemplate.java
  src/main/java/seedu/duke/template/Template.java
  src/main/java/seedu/duke/ui/Ui.java
  src/test/java/seedu/duke/commands/AddCommandTest.java
  src/test/java/seedu/duke/component/LoadComponentTest.java
  src/test/java/seedu/duke/parser/ParserTest.java
  src/test/java/seedu/duke/template/LcTemplateTest.java
  src/test/java/seedu/duke/template/RcTemplateTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High, type.Story

#38 Add calculate command, set voltage source
  docs/UserGuide.md
  src/main/java/seedu/duke/commands/CalculateCommand.java
  src/main/java/seedu/duke/commands/SetCommand.java
  src/main/java/seedu/duke/component/VoltageSource.java
  src/main/java/seedu/duke/parser/Parser.java
  src/main/java/seedu/duke/template/LcTemplate.java
  src/main/java/seedu/duke/template/LrTemplate.java
  src/main/java/seedu/duke/template/RTemplate.java
  src/main/java/seedu/duke/template/RcTemplate.java
  src/main/java/seedu/duke/template/Template.java
  src/main/java/seedu/duke/ui/Ui.java
  src/test/java/seedu/duke/commands/CalculateCommandTest.java
Labels: priority.High, type.Documentation, type.Story

#39 Add Tests to ParserTest
  build.gradle
  src/test/java/seedu/duke/parser/ParserTest.java
  text-ui-test/runtest.bat
Labels: priority.High, type.Task

#41 A-HelpCommand
  build.gradle
  src/main/java/seedu/duke/commands/HelpCommand.java
  src/main/java/seedu/duke/commands/SetCommand.java
  src/main/java/seedu/duke/commands/SummaryCommand.java
  src/main/java/seedu/duke/parser/Parser.java
  src/main/java/seedu/duke/template/RcTemplate.java
  src/main/java/seedu/duke/ui/Ui.java
  src/test/java/seedu/duke/commands/HelpCommandTest.java
  src/test/java/seedu/duke/ui/UiTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
  text-ui-test/runtest.bat
  text-ui-test/runtest.sh
Labels: priority.High, type.Epic, type.Story

#43 Add JUnit Testing For Components
  src/main/java/seedu/duke/component/Component.java
  src/main/java/seedu/duke/component/LoadComponent.java
  src/test/java/seedu/duke/component/CapacitorTest.java
  src/test/java/seedu/duke/component/InductorTest.java
  src/test/java/seedu/duke/component/LoadComponentTest.java
  src/test/java/seedu/duke/component/ResistorTest.java
  src/test/java/seedu/duke/component/VoltageSourceTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
  text-ui-test/runtest.sh
Labels: priority.High, type.Task

#42 Add Tests to Template Tests
  src/main/java/seedu/duke/template/LcTemplate.java
  src/main/java/seedu/duke/template/LrTemplate.java
  src/main/java/seedu/duke/template/RcTemplate.java
  src/main/java/seedu/duke/template/Template.java
  src/test/java/seedu/duke/template/LcTemplateTest.java
  src/test/java/seedu/duke/template/LrTemplateTest.java
  src/test/java/seedu/duke/template/RTemplateTest.java
  src/test/java/seedu/duke/template/RcTemplateTest.java
Labels: priority.High, type.Task

#44 Add JUnit ExitCommandTest
  src/test/java/seedu/duke/commands/ExitCommandTest.java
Labels: priority.Medium, type.Task

#45 Update User Guide v1.0
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ArchitectureDiagram.png
  docs/diagrams/ArchitectureDiagram.puml
Labels: priority.High, type.Documentation

#46 Fix minor readme.md issue
  docs/README.md
Labels: priority.Medium, severity.VeryLow, type.Documentation

#48 Add assertions and modify exceptions
  src/main/java/seedu/duke/component/Component.java
  src/main/java/seedu/duke/component/LoadComponent.java
  src/test/java/seedu/duke/commands/CalculateCommandTest.java
  src/test/java/seedu/duke/component/CapacitorTest.java
  src/test/java/seedu/duke/component/InductorTest.java
  src/test/java/seedu/duke/component/ResistorTest.java
  src/test/java/seedu/duke/component/VoltageSourceTest.java
  src/test/java/seedu/duke/template/LcTemplateTest.java
  src/test/java/seedu/duke/template/LrTemplateTest.java
  src/test/java/seedu/duke/template/RTemplateTest.java
  src/test/java/seedu/duke/template/RcTemplateTest.java
Labels: priority.High, type.Task

#49 Refactor Ui out of Command
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/commands/AddCommand.java
  src/main/java/seedu/duke/commands/CalculateCommand.java
  src/main/java/seedu/duke/commands/Command.java
  src/main/java/seedu/duke/commands/ExitCommand.java
  src/main/java/seedu/duke/commands/HelpCommand.java
  src/main/java/seedu/duke/commands/SetCommand.java
  src/main/java/seedu/duke/commands/SummaryCommand.java
  src/main/java/seedu/duke/commands/TemplateCommand.java
  src/main/java/seedu/duke/parser/Parser.java
  src/main/java/seedu/duke/ui/Ui.java
  src/test/java/seedu/duke/commands/AddCommandTest.java
  src/test/java/seedu/duke/commands/CalculateCommandTest.java
  src/test/java/seedu/duke/commands/ExitCommandTest.java
  text-ui-test/EXPECTED.TXT
Labels: priority.Medium, type.Task

#50 Update Developer Guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ArchitectureDiagram.puml
  docs/diagrams/LogicClassDiagram.png
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ModelClassDiagram.png
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/UiClassDiagram.png
  docs/diagrams/UiClassDiagram.puml
  src/main/java/seedu/duke/ui/Ui.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High, type.Documentation

#52 Add assertions to templates
  src/main/java/seedu/duke/parser/Parser.java
  src/main/java/seedu/duke/template/LcTemplate.java
  src/main/java/seedu/duke/template/LrTemplate.java
  src/main/java/seedu/duke/template/RcTemplate.java
Labels: priority.High, type.Task

#51 Add assertions and logging
  appLog.log
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/commands/AddCommand.java
  src/main/java/seedu/duke/commands/Command.java
  src/main/java/seedu/duke/commands/ExitCommand.java
  src/main/java/seedu/duke/commands/HelpCommand.java
  src/main/java/seedu/duke/commands/TemplateCommand.java
  src/main/java/seedu/duke/parser/Parser.java
Labels: priority.High, type.Task

#53 Add BinaryTree
  src/main/java/seedu/duke/template/BinaryTree.java
  src/main/java/seedu/duke/template/BooleanTemplate.java
Labels: priority.High, type.Task

#54 Add printTree function to Binary Tree
  appLog.log
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/component/gates/AndGate.java
  src/main/java/seedu/duke/component/gates/Gate.java
  src/main/java/seedu/duke/component/gates/TwoInputGate.java
  src/main/java/seedu/duke/template/BinaryTree.java
  src/main/java/seedu/duke/template/BooleanTemplate.java
  text-ui-test/appLog.log
Labels: priority.High, type.Enhancement

#56 Add OR, NOT, and XOR gates
  src/main/java/seedu/duke/component/gates/NotGate.java
  src/main/java/seedu/duke/component/gates/OrGate.java
  src/main/java/seedu/duke/component/gates/XorGate.java
  src/main/java/seedu/duke/template/BinaryTree.java
  src/main/java/seedu/duke/template/LcTemplate.java
  src/main/java/seedu/duke/template/RcTemplate.java
  src/test/java/seedu/duke/commands/HelpCommandTest.java
  text-ui-test/input.txt
Labels: priority.High, type.Enhancement

#58 JUnit testing for the remaining commands
  src/main/java/seedu/duke/template/BinaryTree.java
  src/test/java/seedu/duke/commands/HelpCommandTest.java
  src/test/java/seedu/duke/commands/SetCommandTest.java
Labels: priority.High, type.Task

#61 Update Documentation
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ArchitectureDiagram.png
  docs/diagrams/ModelClassDiagram.png
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/SetSequenceDiagram.png
  docs/diagrams/SetSequenceDiagram.puml
  docs/team/wira.md
Labels: priority.High, type.Documentation

#63 DG Updates: Added 'Getting started', NFRs, and 'Instructions for Manual Testing'
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.Medium, type.Documentation

#71 Refactor, Add BooleanCommand, BooleanParser
  src/main/java/seedu/duke/logic/commands/Command.java
  src/main/java/seedu/duke/logic/commands/circuit/AddCircuitCommand.java
  src/main/java/seedu/duke/logic/commands/circuit/CalculateCircuitCommand.java
  src/main/java/seedu/duke/logic/commands/circuit/CircuitCommand.java
  src/main/java/seedu/duke/logic/commands/circuit/HelpCircuitCommand.java
  src/main/java/seedu/duke/logic/commands/circuit/SetCircuitCommand.java
  src/main/java/seedu/duke/logic/commands/circuit/TemplateCircuitCommand.java
  src/main/java/seedu/duke/logic/commands/gates/AddBooleanCommand.java
  src/main/java/seedu/duke/logic/commands/gates/BooleanCommand.java
  src/main/java/seedu/duke/logic/commands/gates/CalculateBooleanCommand.java
  src/main/java/seedu/duke/logic/commands/gates/SetBooleanCommand.java
  src/main/java/seedu/duke/logic/commands/gates/TemplateBooleanCommand.java
  src/main/java/seedu/duke/logic/parser/BooleanParser.java
  src/main/java/seedu/duke/logic/parser/CircuitParser.java
  src/main/java/seedu/duke/logic/parser/Parser.java
  src/main/java/seedu/duke/model/binarytree/BinaryTree.java
  src/main/java/seedu/duke/model/gates/AndGate.java
  src/main/java/seedu/duke/model/gates/Gate.java
  src/main/java/seedu/duke/model/gates/NandGate.java
  src/main/java/seedu/duke/model/gates/NorGate.java
  src/main/java/seedu/duke/model/gates/NotGate.java
  src/main/java/seedu/duke/model/gates/OrGate.java
  src/main/java/seedu/duke/model/gates/TwoInputGate.java
  src/main/java/seedu/duke/model/gates/XnorGate.java
  src/main/java/seedu/duke/model/gates/XorGate.java
  src/main/java/seedu/duke/model/template/BooleanTemplate.java
  src/main/java/seedu/duke/model/template/CircuitTemplate.java
  src/main/java/seedu/duke/model/template/LcTemplate.java
  src/main/java/seedu/duke/model/template/RTemplate.java
  src/test/java/seedu/duke/logic/ExitCommandTest.java
  src/test/java/seedu/duke/logic/commands/HelpCommandTest.java
  src/test/java/seedu/duke/logic/commands/circuit/AddCircuitCommandTest.java
  src/test/java/seedu/duke/logic/commands/circuit/CalculateCircuitCommandTest.java
  src/test/java/seedu/duke/logic/commands/circuit/SetCircuitCommandTest.java
  src/test/java/seedu/duke/logic/parser/ParserTest.java
  text-ui-test/appLog.log
Labels: priority.High, type.Task

#73 A dev guide
  appLog.log
  docs/DeveloperGuide.md
  docs/diagrams/BinaryTreeInitialObjectDiagram.png
  docs/diagrams/BinaryTreeInitialObjectDiagram.puml
  docs/diagrams/BinaryTreeInsertSequenceDiagram.png
  docs/diagrams/BinaryTreeInsertSequenceDiagram.puml
  docs/diagrams/BinaryTreeIsEmptySequenceDiagram.png
  docs/diagrams/BinaryTreeIsEmptySequenceDiagram.puml
  docs/diagrams/BinaryTreeIsLeafSequence.png
  docs/diagrams/BinaryTreeIsLeafSequence.puml
  src/main/java/seedu/duke/model/binarytree/BinaryTree.java
  src/main/java/seedu/duke/model/template/BooleanTemplate.java
Labels: priority.High, type.Documentation, type.Enhancement

#74 Update to DG: Fixed some bugs in ToC
  docs/DeveloperGuide.md
  docs/SettingUp.md
Labels: priority.Medium, severity.VeryLow, type.Bug, type.Documentation

#76 Change names in DG from 'Duke' to 'CLIrcuit Assistant'
  docs/DeveloperGuide.md
  docs/SettingUp.md
Labels: priority.High, type.Documentation

#77 Fixed broken toc link for Design & Implementation
  docs/DeveloperGuide.md
Labels: priority.High, type.Documentation

#79 A update toc
  appLog.log
  docs/DeveloperGuide.md
  text-ui-test/appLog.log
Labels: priority.High, type.Documentation

#78 Minor change to ASCII art in main README
  README.md
Labels: priority.Medium, type.Documentation

#62 Dev Guide Updates
  .gitignore
  appLog.log
  docs/DeveloperGuide.md
  docs/diagrams/AddSequenceDiagram.png
  docs/diagrams/AddSequenceDiagram.puml
  docs/diagrams/CalcPowerSequenceDiagram.png
  docs/diagrams/CalcPowerSequenceDiagram.puml
  docs/diagrams/CalcReffSequenceDiagram.png
  docs/diagrams/CalcReffSequenceDiagram.puml
  docs/diagrams/TemplateSequenceDiagram.png
  docs/diagrams/TemplateSequenceDiagram.puml
Labels: priority.High, type.Documentation

#82 Add Boolean Logic
  src/main/java/seedu/duke/logic/commands/gates/AddBooleanCommand.java
  src/main/java/seedu/duke/logic/commands/gates/SetBooleanCommand.java
  src/main/java/seedu/duke/logic/parser/BooleanParser.java
  src/main/java/seedu/duke/logic/parser/CircuitParser.java
  src/main/java/seedu/duke/model/binarytree/BinaryTree.java
  src/main/java/seedu/duke/model/template/BooleanTemplate.java
Labels: priority.High, type.Story

#83 Add Template, Add, Set BooleanCommand functionalities
  src/main/java/seedu/duke/logic/commands/ExitCommand.java
  src/main/java/seedu/duke/logic/commands/SummaryCommand.java
  src/main/java/seedu/duke/logic/commands/circuit/AddCircuitCommand.java
  src/main/java/seedu/duke/logic/commands/circuit/CalculateCircuitCommand.java
  src/main/java/seedu/duke/logic/commands/circuit/HelpCircuitCommand.java
  src/main/java/seedu/duke/logic/commands/circuit/SetCircuitCommand.java
  src/main/java/seedu/duke/logic/commands/circuit/TemplateCircuitCommand.java
  src/main/java/seedu/duke/logic/commands/gates/AddBooleanCommand.java
  src/main/java/seedu/duke/logic/commands/gates/CalculateBooleanCommand.java
  src/main/java/seedu/duke/logic/commands/gates/SetBooleanCommand.java
  src/main/java/seedu/duke/logic/commands/gates/TemplateBooleanCommand.java
  src/main/java/seedu/duke/logic/parser/BooleanParser.java
  src/main/java/seedu/duke/logic/parser/CircuitParser.java
  src/main/java/seedu/duke/logic/parser/LogicParser.java
  src/main/java/seedu/duke/logic/parser/Parser.java
  src/main/java/seedu/duke/model/binarytree/BinaryTree.java
  src/main/java/seedu/duke/model/gates/AndGate.java
  src/main/java/seedu/duke/model/gates/Gate.java
  src/main/java/seedu/duke/model/gates/NandGate.java
  src/main/java/seedu/duke/model/gates/NorGate.java
  src/main/java/seedu/duke/model/gates/NotGate.java
  src/main/java/seedu/duke/model/gates/OrGate.java
  src/main/java/seedu/duke/model/gates/TwoInputGate.java
  src/main/java/seedu/duke/model/gates/XnorGate.java
  src/main/java/seedu/duke/model/gates/XorGate.java
  src/main/java/seedu/duke/model/template/BooleanTemplate.java
  src/test/java/seedu/duke/model/template/BooleanTemplateTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High, type.Story

#90 A-Boolean Parser
  docs/DeveloperGuide.md
  src/main/java/seedu/duke/logic/commands/TutorialCommand.java
  src/main/java/seedu/duke/logic/commands/circuit/TutorialCircuitCommand.java
  src/main/java/seedu/duke/logic/commands/gates/TutorialBooleanCommand.java
  src/main/java/seedu/duke/logic/parser/BooleanParser.java
  src/main/java/seedu/duke/logic/parser/CircuitParser.java
  src/main/java/seedu/duke/logic/parser/Parser.java
  src/test/java/seedu/duke/logic/parser/ParserTest.java
  text-ui-test/appLog.log
  text-ui-test/input.txt
Labels: priority.High, type.Task

#91 Update Documentation
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddAndOrXORGates.png
  docs/diagrams/AddBooleanCommand.png
  docs/diagrams/AddBooleanCommand.puml
  docs/diagrams/AddBooleanCommandSeqDiagram.png
  docs/diagrams/AddOrAndGates.png
  docs/diagrams/AddSequenceDiagram.png
  docs/diagrams/AddSequenceDiagram.puml
  docs/diagrams/ArchitectureDiagram.png
  docs/diagrams/ArchitectureDiagram.puml
  docs/diagrams/CalcBooleanCommand.png
  docs/diagrams/CalcBooleanCommand.puml
  docs/diagrams/CalcPowerSequenceDiagram.png
  docs/diagrams/CalcPowerSequenceDiagram.puml
  docs/diagrams/CalcReffSequenceDiagram.png
  docs/diagrams/CalcReffSequenceDiagram.puml
  docs/diagrams/CircuitClassDiagram.png
  docs/diagrams/CircuitClassDiagram.puml
  docs/diagrams/CommandUserDiagram.png
  docs/diagrams/LogicClassDiagram.png
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ModelClassDiagram.png
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/OrGateClassDiagram.png
  docs/diagrams/OrGateObjectDiagram.png
  docs/diagrams/SetBooleanCommand.puml
  docs/diagrams/SetSequenceDiagram.png
  docs/diagrams/SetSequenceDiagram.puml
  docs/diagrams/TemplateBooleanCommand.png
  docs/diagrams/TemplateSequenceDiagram.png
  docs/diagrams/TemplateSequenceDiagram.puml
  docs/diagrams/UiClassDiagram.png
  docs/diagrams/UiClassDiagram.puml
  docs/diagrams/UiSequenceDiagram.png
  docs/diagrams/UiSequenceDiagram.puml
  docs/diagrams/calcObjectDiagram.png
  docs/diagrams/setBooleanCommand.png
Labels: priority.High, type.Documentation

#92 Add Boolean Calculation Command
  src/main/java/seedu/duke/logic/commands/gates/CalculateBooleanCommand.java
  src/main/java/seedu/duke/logic/parser/BooleanParser.java
  src/main/java/seedu/duke/model/gates/AndGate.java
  src/main/java/seedu/duke/model/gates/Gate.java
  src/main/java/seedu/duke/model/gates/NandGate.java
  src/main/java/seedu/duke/model/gates/NorGate.java
  src/main/java/seedu/duke/model/gates/NotGate.java
  src/main/java/seedu/duke/model/gates/OrGate.java
  src/main/java/seedu/duke/model/gates/TwoInputGate.java
  src/main/java/seedu/duke/model/gates/XnorGate.java
  src/main/java/seedu/duke/model/gates/XorGate.java
  src/main/java/seedu/duke/model/template/BooleanTemplate.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High, type.Enhancement

#94 Update Summary Command
  src/main/java/seedu/duke/logic/commands/SummaryCommand.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High, type.Story

#93 Issue #88, Update HelpCircuitCommand
  src/main/java/seedu/duke/logic/commands/SummaryCommand.java
  src/main/java/seedu/duke/logic/commands/circuit/TutorialCircuitCommand.java
  src/main/java/seedu/duke/model/template/CircuitTemplate.java
  src/main/java/seedu/duke/model/template/LcTemplate.java
  src/main/java/seedu/duke/model/template/LrTemplate.java
  src/main/java/seedu/duke/model/template/RTemplate.java
  src/main/java/seedu/duke/model/template/RcTemplate.java
  src/main/java/seedu/duke/ui/Ui.java
  src/test/java/seedu/duke/logic/parser/ParserTest.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High, type.Task

#102 JUnit tests for BinaryTree
  src/test/java/seedu/duke/model/binarytree/BinaryTreeTest.java
Labels: priority.High

#103 Add BooleanTutorialCommand
  src/main/java/seedu/duke/logic/commands/SummaryCommand.java
  src/main/java/seedu/duke/logic/commands/circuit/TutorialCircuitCommand.java
  src/main/java/seedu/duke/logic/commands/gates/TutorialBooleanCommand.java
  src/main/java/seedu/duke/ui/Ui.java
  src/test/java/seedu/duke/ui/UiTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High, type.Story

#101 Update DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.High, type.Documentation

#100 Update Ui
  src/main/java/seedu/duke/Duke.java
  src/main/java/seedu/duke/ui/Ui.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: priority.High, type.Task

#105 A - JUnits
  src/test/java/seedu/duke/logic/commands/gates/CalculateBooleanCommandTest.java
  src/test/java/seedu/duke/model/binarytree/BinaryTreeTest.java
Labels: priority.High, type.Task

#106 Add SetBooleanCommandTest
  src/test/java/seedu/duke/logic/commands/gates/SetBooleanCommandTest.java
Labels: priority.High, type.Task

#109 Update Documentation
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/BooleanCommandClassDiagram.png
  docs/diagrams/BooleanCommandClassDiagram.puml
  docs/diagrams/BooleanCommandClassDiagran.png
  docs/diagrams/CircuitClassDiagram.png
  docs/diagrams/CircuitCommandClassDiagram.png
  docs/diagrams/CircuitCommandClassDiagram.puml
  docs/diagrams/CircuitModelClassDiagram.png
  docs/diagrams/CircuitModelClassDiagram.puml
  docs/team/hughjazzman.md
  docs/team/wira.md
Labels: priority.High, type.Documentation

#111 Update Docs
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/team/sevenseasofbri.md
Labels: priority.Medium, type.Documentation

#112 update input.txt
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
Labels: severity.Medium, type.Bug

#113 Update to Kramdown
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/README.md
  docs/UserGuide.md
  docs/_config.yml
  docs/diagrams/BooleanCLI.png
  docs/diagrams/CircuitCLI.png
  docs/diagrams/github-icon.png
  docs/index.md
  docs/team/hughjazzman.md
  src/main/java/seedu/duke/ui/Ui.java
  text-ui-test/EXPECTED.TXT
Labels: priority.Medium, type.Documentation

#114 remove print command
  src/main/java/seedu/duke/logic/commands/SummaryCommand.java
  text-ui-test/EXPECTED.TXT
Labels: severity.Low, type.Bug

#115 update bye
  src/main/java/seedu/duke/logic/commands/SummaryCommand.java
  text-ui-test/EXPECTED.TXT
Labels: severity.Low, type.Bug

#119 Update UML Diagrams
  docs/DeveloperGuide.md
  docs/diagrams/AddBooleanCommand.png
  docs/diagrams/AddBooleanCommand.puml
  docs/diagrams/AddBooleanCommandObjectDiagram.png
  docs/diagrams/AddBooleanCommandObjectDiagram.puml
  docs/diagrams/AddCommandOrAnd.png
  docs/diagrams/AddCommandOrAnd.puml
  docs/diagrams/AddCommandOrAndXor.png
  docs/diagrams/AddCommandOrAndXor.puml
  docs/diagrams/AddSequenceDiagram.png
  docs/diagrams/AddSequenceDiagram.puml
  docs/diagrams/ArchitectureDiagram.puml
  docs/diagrams/BinaryTreeInitialObjectDiagram.png
  docs/diagrams/BinaryTreeInitialObjectDiagram.puml
  docs/diagrams/BooleanCommandClassDiagram.png
  docs/diagrams/BooleanCommandClassDiagram.puml
  docs/diagrams/CalcBooleanCommand.png
  docs/diagrams/CalcBooleanCommand.puml
  docs/diagrams/CalcReffSequenceDiagram.png
  docs/diagrams/CalcReffSequenceDiagram.puml
  docs/diagrams/CircuitCommandClassDiagram.png
  docs/diagrams/CircuitCommandClassDiagram.puml
  docs/diagrams/CircuitModelClassDiagram.png
  docs/diagrams/CircuitModelClassDiagram.puml
  docs/diagrams/LogicClassDiagram.png
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ModelClassDiagram.png
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/OrGateClassDiagram.png
  docs/diagrams/OrGateClassDiagram.puml
  docs/diagrams/OrGateObjectDiagram.png
  docs/diagrams/OrGateObjectDiagram.puml
  docs/diagrams/SetBooleanCommand.png
  docs/diagrams/SetBooleanCommand.puml
  docs/diagrams/TemplateBooleanCommand.png
  docs/diagrams/TemplateBooleanCommand.puml
  docs/diagrams/TemplateSequenceDiagram.png
  docs/diagrams/TemplateSequenceDiagram.puml
  docs/diagrams/UiClassDiagram.png
  docs/diagrams/UiClassDiagram.puml
  docs/diagrams/style.puml
Labels: priority.High, severity.Medium, type.Bug, type.Documentation

#121 Update DG with Code Review
  docs/DeveloperGuide.md
  docs/diagrams/AddBooleanCommandObjectDiagram.png
  docs/diagrams/AddBooleanCommandObjectDiagram.puml
  docs/diagrams/AddCommandOrAnd.png
  docs/diagrams/AddCommandOrAnd.puml
  docs/diagrams/AddCommandOrAndXor.png
  docs/diagrams/AddCommandOrAndXor.puml
  docs/diagrams/AddSequenceDiagram.png
  docs/diagrams/AddSequenceDiagram.puml
  docs/diagrams/BooleanCommandClassDiagram.png
  docs/diagrams/BooleanCommandClassDiagram.puml
  docs/diagrams/BooleanTemplateClassDiagram.png
  docs/diagrams/BooleanTemplateClassDiagram.puml
  docs/diagrams/CalcBooleanCommand.png
  docs/diagrams/CalcBooleanCommand.puml
  docs/diagrams/CalcPowerSequenceDiagram.png
  docs/diagrams/CalcPowerSequenceDiagram.puml
  docs/diagrams/CalcReffSequenceDiagram.png
  docs/diagrams/CalcReffSequenceDiagram.puml
  docs/diagrams/CircuitCommandClassDiagram.png
  docs/diagrams/CircuitCommandClassDiagram.puml
  docs/diagrams/CircuitModelClassDiagram.png
  docs/diagrams/CircuitModelClassDiagram.puml
  docs/diagrams/GateClassDiagram.png
  docs/diagrams/GateClassDiagram.puml
  docs/diagrams/GetCommand.png
  docs/diagrams/GetCommand.puml
  docs/diagrams/GetComponent.png
  docs/diagrams/GetComponent.puml
  docs/diagrams/OrGateClassDiagram.png
  docs/diagrams/OrGateClassDiagram.puml
  docs/diagrams/OrGateObjectDiagram.png
  docs/diagrams/OrGateObjectDiagram.puml
  docs/diagrams/SetSequenceDiagram.png
  docs/diagrams/SetSequenceDiagram.puml
  docs/diagrams/TemplateBooleanCommand.png
  docs/diagrams/TemplateBooleanCommand.puml
  docs/diagrams/TemplateSequenceDiagram.png
  docs/diagrams/TemplateSequenceDiagram.puml
Labels: priority.High, severity.Low, type.Bug, type.Documentation

#122 Update diagrams based on reviews
  docs/diagrams/BinaryTreeInitialObjectDiagram.png
  docs/diagrams/BinaryTreeInitialObjectDiagram.puml
  docs/diagrams/BinaryTreeInsertSequenceDiagram.png
  docs/diagrams/BinaryTreeInsertSequenceDiagram.puml
Labels: severity.Medium, type.Bug, type.Documentation
